package org.softtech.infrastructure.entrypoints.rest.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.Builder;
import lombok.extern.jackson.Jacksonized;
import org.eclipse.microprofile.openapi.annotations.media.Schema;

import java.time.Instant;
import java.util.Map;



/**
 * Immutable Data Transfer Object (DTO) capturing standardized HTTP error payloads.
 * <p>
 * Strictly implements the IETF RFC 7807 / RFC 9457 (Problem Details for HTTP APIs) standard specification.
 * It provides a uniform machine-readable and human-diagnosable contract across all error responses emitted
 * by the HelpDesk reactive microservice, encapsulating business exception codes, HTTP status semantics,
 * localized violation maps for bean validation, and distributed correlation identifiers for observability.
 * </p>
 * <p>
 * In strict compliance with ISO/IEC 25010 Reliability (Fault Tolerance, Analyzability) and CMMI Level 2/3
 * Verification & Defect Management standards, this record is shallowly immutable, Jacksonized,
 * and serialized without intermediate runtime reflection overhead on the Netty Event Loop.
 * </p>
 *
 * @param type an absolute URI reference identifying the specific error category/problem type
 * @param title a short, human-readable summary of the problem type (e.g., "Ticket Not Found")
 * @param status the HTTP status code generated by the origin server for this occurrence
 * @param detail a human-readable explanation specific to this occurrence of the problem
 * @param instance a URI reference that identifies the specific resource occurrence (e.g., "/api/v1/tickets/TICK-2026-0001")
 * @param errorCode the internal business error classification code (e.g., "ERR_TICKET_NOT_FOUND")
 * @param violations an optional map of field-level validation errors (field name to violation message)
 * @param correlationId the distributed tracing identifier (MDC / X-Correlation-ID) for end-to-end log correlation
 * @param timestamp the exact UTC instant when the error occurred
 *
 */
@Builder(toBuilder = true)
@Jacksonized
@JsonInclude(JsonInclude.Include.NON_NULL)
@Schema(
        name = "ErrorResponseDto",
        description = "Standard RFC 7807 / FRC 9457 Problem Details error payload representation."
)
public record ErrorResponseDto(
        @Schema(
                description = "URI reference identifying the problem classification category.",
                examples = {"https://helpdesk.softtech.com/errors/not-found"}
        )
        String type,


        @Schema(
                description = "Short, human-readable summary of the HTTP problem.",
                examples = {"Ticket not found"}
        )
        String title,

        @Schema(
                description = "HTTP status code matching the response headers.",
                examples = {"404"}
        )
        int status,

        @Schema(
                description = "Detailed human-readable explanation specific to this error occurrence.",
                examples = {"The support ticket with business number [TICK-2026-0001] was not found in persistence or cache."}
        )
        String detail,

        @Schema(
                description = "URI path of the HTTP request endpoint that generated the error.",
                examples = {"/api/v1/tickets/number/TICK-2026-0001"}
        )
        String instance,

        @Schema(
                description = "Canonical internal business error code.",
                examples = {"ERR_TICKET_NOT_FOUND"}
        )
        String errorCode,

        @Schema(
                description = "Map of field-level constraint violations for HTTP 400 Bad responses.",
                examples = {"{\"title\": \"Ticket title must not be blank\", \"priority\": \"Ticket priority must not be null\"}"},
                nullable = true
        )
        Map<String, String> violations,

        @Schema(
                description = "Distributed correlation identifier for observability and log tracing",
                examples = {"c3d9a1f4-8b2e-4e71-9c63-1a2b3c4d5e6f"}
        )
        String correlationId,


        @Schema(
                description = "Exact UTC timestamp when the error occurred.",
                examples = {"2026-08-27T11:45:00Z"}
        )
        Instant timestamp
) {
}
